#!/bin/zsh

crchpid=""
for finst in $(playerctl -l | grep "firefox")
do
  [[ $(playerctl -p $finst metadata title | grep "Crunchyroll") ]] && \
    crchpid="$(echo $finst | cut -c 17-)"
done

if [ -z "$crchpid" ]; then
  echo "No running firefox instance with \e[1;33mCruncyroll\e[0m" >&2
  exit 1
fi


for id in $(bspc query -N -n .window)
  [[ $( echo "$(xprop -id $id)" | grep "_NET_WM_PID(CARDINAL) = $crchpid" ) ]] && \ 
    playerctl -p "firefox.instance$crchpic" play && bspc node -f $id && \
    echo "\e[1;32mSuccess!\e[0m An instance (\e[1;35mPID\e[0m=\e[1;35m$crchpid\e[0m) of Firefox with \e[1;33mCrunchyroll\e[0m was found and has been started!" && \
    (xdotool sleep 2 ; xdotool key f) \
    && exit 0

echo "\e[1;31mFATAL:\e[0m could not get WM_DESKTOP(CARDINAL) or NODE ID." >&2
exit 1
